name: test CD

on:
  push:
    tags:
        - v*-SNAPSHOT

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
            - 12.0.0

    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
              node-version: ${{ matrix.node-version }}
        - name: Deploy Front Stage        
          working-directory: ./front-stage
          run: echo -n '${{ secrets.GCS_TUTOR_TEST }}' > tutor-test.json && npm install && npm run uploadGcsTest
        - name: Deploy Back Stage
          working-directory: ./back-stage          
          run: echo -n '${{ secrets.GCS_TUTOR_TEST }}' > tutor-test.json && npm install && npm run uploadGcsTest
