name: test CD

on:
  push:
    tags:
        - v*-SNAPSHOT
defaults:
  run:
    working-directory: front-stage

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
            - 12.0.0
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
              node-version: ${{ matrix.node-version }}
        - run: echo -n '${{ secrets.GCS_TUTOR_TEST }}' > tutor-test.json
        - run: ls
        - run: npm install
        - run: npm run uploadGcsTest


