name: production CD

on:
  push:
    tags:
        - v\d+\.\d+\.\d+

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
            - 12.0.0

    steps:
        - uses: actions/checkout@v2
        - name: Front Stage Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          working-directory: ./front-stage
          with:
              node-version: ${{ matrix.node-version }}          
          run: echo -n '${{ secrets.GCS_TUTOR_TEST }}' > tutor.json && npm install && npm run uploadGcsProd
        - name: Back Stage Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          working-directory: ./back-stage
          with:
              node-version: ${{ matrix.node-version }}
          run: echo -n '${{ secrets.GCS_TUTOR_TEST }}' > tutor.json && npm install && npm run uploadGcsProd