name: test CD

on:
  push:
    tags:
        - v*-SNAPSHOT

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
            - 12.0.0

    steps:
        - uses: actions/checkout@v2
        - name: Front Stage Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          working-directory: ./front-stage
          with:
              node-version: ${{ matrix.node-version }}          
          run: echo -n '${{ secrets.GCS_TUTOR_TEST }}' > tutor-test.json && npm install && npm run uploadGcsTest
        - name: Back Stage Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          working-directory: ./back-stage
          with:
              node-version: ${{ matrix.node-version }}
          run: echo -n '${{ secrets.GCS_TUTOR_TEST }}' > tutor-test.json && npm install && npm run uploadGcsTest
